[package]
name = "bones-quest"
version = "0.1.0"
authors = ["Nicholas Farley <nicholasafarley@gmail.com>"]
publish = false

[dependencies]
ggez = "0.4.1"
toml = "0.4.5"
serde_derive = "1.0.33"
serde = "1.0.33"
regex = "0.2.10"
