[[command]]
  id = "blood-begin"
  text = "THIS IS A STORY OF A DAY WHERE THERE WAS ALL THIS BLOOD."
  [command.menu]
    "I don't expect anyone to kill me" = "GET_KILLED"
    "I expect to die at any moment!" = "ALSO_GET_KILLED"
  [command.portrait]
    t = "Show"
    c = ["Yare", "Daze"]
  [command.background]
    t = "Color"
    c = "#ff0000"
  [command.positions]
    Jotaro = { direction = 'L', position = -40 }
    Dio = { direction = 'R', position = 70 }

[[command]]
  id = "blood-second"
  text = "A MAN WAS WALKING AROUND AND BLOOD STARTED COMING OUT OF HIM EVERYWHERE."

[[command]]
  id = "GET_KILLED"
  text = "THERE WAS SO MUCH BLOOD THAT IT FILLED UP AN ELEVATOR."

[[command]]
  id = "ALSO_GET_KILLED"
  text = "HE WENT TO THE STORE AND THERE WAS JUST BLOOD ALL OVER THE PLACE!"

[[command]]
  text = "PEOPLE WERE SLIPPING IN IT AND THEY WERE ALL GROSSED OUT."

[[command]]
  text = "HE TRIED TO GO SWIMMING AND ALL OF THE SHARKS WENT NUTS AND BITTENED EVERYBODY."

[[command]]
  text = "HE GOT CHASED BY ALL THE VAMPIRES EVER."

[[command]]
  text = "ONE TIME THE BLOOD GOT A KID AND A DOG."

[[command]]
  text = "AT THE END OF THE DAY EVERYONE DECIDED THEY WOULD SEND HIM TO SPACE SO THAT HE WOULD STOP GETTING BLOOD EVERY WHERE."

[[command]]
  id = "blood-end"
  text = "THE SCARIEST PART IS THAT THE MAN WAS YOU!!! (OR HE WAS A LADY IF YOU ARE A LADY) AND YOU FORGOT THAT THIS HAPPENED."
