[[command]]
  text = "THIS IS A STORY OF A DAY WHERE THERE WAS ALL THIS BLOOD."
  [command.portrait]
    t = "Show"
    c = ["Yare", "Daze"]
  [command.background]
    t = "Color"
    c = "#ff0000"
  [command.positions]
    Jotaro = { direction = 'L', position = 0 }
    Dio = { direction = 'R', position = -100 }

[[command]]
  text = "A MAN WAS WALKING AROUND AND BLOOD STARTED COMING OUT OF HIM EVERYWHERE."

[[command]]
  text = "THERE WAS SO MUCH BLOOD THAT IT FILLED UP AN ELEVATOR."

[[command]]
  text = "HE WENT TO THE STORE AND THERE WAS JUST BLOOD ALL OVER THE PLACE!"

[[command]]
  text = "PEOPLE WERE SLIPPING IN IT AND THEY WERE ALL GROSSED OUT."

[[command]]
  text = "HE TRIED TO GO SWIMMING AND ALL OF THE SHARKS WENT NUTS AND BITTENED EVERYBODY."

[[command]]
  text = "HE GOT CHASED BY ALL THE VAMPIRES EVER."

[[command]]
  text = "ONE TIME THE BLOOD GOT A KID AND A DOG."

[[command]]
  text = "AT THE END OF THE DAY EVERYONE DECIDED THEY WOULD SEND HIM TO SPACE SO THAT HE WOULD STOP GETTING BLOOD EVERY WHERE."

[[command]]
  text = "THE SCARIEST PART IS THAT THE MAN WAS YOU!!! (OR HE WAS A LADY IF YOU ARE A LADY) AND YOU FORGOT THAT THIS HAPPENED."
