[[commands]]
text = "THIS IS A STORY OF A DAY WHERE THERE WAS ALL THIS BLOOD."

[[commands]]
text = "A MAN WAS WALKING AROUND AND BLOOD STARTED COMING OUT OF HIM EVERYWHERE."

[[commands]]
text = "THERE WAS SO MUCH BLOOD THAT IT FILLED UP AN ELEVATOR."

[[commands]]
text = "HE WENT TO THE STORE AND THERE WAS JUST BLOOD ALL OVER THE PLACE!"

[[commands]]
text = "PEOPLE WERE SLIPPING IN IT AND THEY WERE ALL GROSSED OUT."

[[commands]]
text = "HE TRIED TO GO SWIMMING AND ALL OF THE SHARKS WENT NUTS AND BITTENED EVERYBODY."

[[commands]]
text = "HE GOT CHASED BY ALL THE VAMPIRES EVER."

[[commands]]
text = "ONE TIME THE BLOOD GOT A KID AND A DOG."

[[commands]]
text = "AT THE END OF THE DAY EVERYONE DECIDED THEY WOULD SEND HIM TO SPACE SO THAT HE WOULD STOP GETTING BLOOD EVERY WHERE."

[[commands]]
text = "THE SCARIEST PART IS THAT THE MAN WAS YOU!!! (OR HE WAS A LADY IF YOU ARE A LADY) AND YOU FORGOT THAT THIS HAPPENED."
