#!/usr/bin/env bash

for FILE in $(git diff --name-only --cached); do
  [ "$(echo "$FILE" | awk -F . '{print $NF}')" != 'rs' ] && exit 0

  if ! rustfmt +nightly "$FILE" --check > /dev/null 2>&1; then
    echo "'$FILE' has rust style issues. Run 'cargo +nightly fmt' and then restage!"
    exit 1
  fi
done
