#!/usr/bin/env sh

has_style_issue=false
for filename in $(git diff --name-only --cached); do
  [ "$(echo "$filename" | awk -F . '{print $NF}')" != 'rs' ] && exit 0

  if ! rustfmt --check "$filename" > /dev/null 2>&1; then
    if ! "$has_style_issue"; then
      has_style_issue=true
      echo ERROR: pre-commit: The following files have style issues
    fi
    echo "- $filename"
  fi
done

"$has_style_issue" && exit 1
